### ISSUE TITLE
Glyph bounding box does not work

### ISSUE THREAD

**Issue by kelvin13** [rougier/freetype-py#35]
All values in glyph bounding boxes accessed from `FT.glyph.get_glyph().get_cbox(0)` return `0`. Probably caused by the fact that every point in `Outline._FT_Outline.points` returns `(0, 0)`.

**Comment by rougier** [comment]
Would you a small script and a (free) front that show the problem ?

**Comment by kelvin13** [comment]
```
import freetype

F = freetype.Face('FiraSans-Book.otf')

F.load_char('R')
G = F.glyph.get_glyph()
CB = G.get_cbox(freetype.FT_GLYPH_BBOX_UNSCALED)

print(CB.xMax, CB.xMin, CB.yMax, CB.yMin)

>>> 0 0 0 0

```

**Comment by rougier** [comment]
The get_bbox also returns 0 0 0 0 ?

**Comment by kelvin13** [comment]
Same problem:
````
import freetype

F = freetype.Face('FiraSans-Book.otf')

F.load_char('R')
G = F.glyph.get_glyph()
CB = G.get_cbox(freetype.FT_GLYPH_BBOX_UNSCALED)

O = F.glyph.outline
BB = O.get_bbox()

print(CB.xMax, CB.xMin, CB.yMax, CB.yMin)
print(BB.xMax, BB.xMin, BB.yMax, BB.yMin)

>>> 0 0 0 0
>>> 0 0 0 0

````

**Comment by kelvin13** [comment]
in all honesty i think the bounding box is working fine something in the library is just telling it that every point in the glyph is at (0, 0)

**Comment by rougier** [comment]
What is weird is that on my side I need to setup the face size (or I get invalid size handle) but you don't seem to need it, right ?

**Comment by kelvin13** [comment]
Nope, I’m using `FT_GLYPH_BBOX_UNSCALED`. Shouldn't font units be independent of face size?

**Comment by kelvin13** [comment]
Other functions work fine without the face size:
````
import freetype

F = freetype.Face('FiraSans-Book.otf')

F.load_char('R')
G = F.glyph.get_glyph()
CB = G.get_cbox(freetype.FT_GLYPH_BBOX_UNSCALED)

O = F.glyph.outline
BB = O.get_bbox()

print(CB.xMax, CB.xMin, CB.yMax, CB.yMin)
print(BB.xMax, BB.xMin, BB.yMax, BB.yMin)

print(F.get_advance(F.get_char_index('R'), True))

>>> 0 0 0 0
>>> 0 0 0 0
>>> 601
````

**Comment by kelvin13** [comment]
F.get_kern(…) also fails in the same way—it just spits out zero-vectors

**Comment by rougier** [comment]
Just to be sure, can you try with the `Vera.ttf` in the examples directory ?
This is what I get:

```
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    face.load_char(' ')
  File "/usr/local/lib/python3.5/site-packages/freetype_py-1.0.2-py3.5.egg/freetype/__init__.py", line 1267, in load_char
freetype.ft_errors.FT_Exception: FT_Exception:  (invalid size handle)
```

from

```
import freetype

face = freetype.Face('Vera.ttf')
face.load_char(' ')
glyph = face.glyph.get_glyph()
box = glyph.get_cbox(freetype.FT_GLYPH_BBOX_UNSCALED)
print(box.xMax, box.xMin, box.yMax, box.yMin)
```

**Comment by kelvin13** [comment]
Vera fails just like you say it does. Tried some other fonts, for some reason it only happens with .ttf fonts. Otf fonts load fine.

**Comment by rougier** [comment]
So next step would be to test your example without the pythonic layer, just raw call to the library.
Could you test that ? If not,  can try but I will lack time in the next few days

**Comment by kelvin13** [comment]
i don’t know how to do that

**Comment by rougier** [comment]
Ok, I will do it (don't hesitate to ping me here)
