### ISSUE TITLE
Accept path-like objects

### ISSUE THREAD

**Issue by madig** [rougier/freetype-py#83]
Currently, passing a Path (args.old_font) to e.g. Face() raises an exception:
```
Traceback (most recent call last):
  File ".\glyphdiff\fttest.py", line 43, in <module>
    old_font_ft = freetype.Face(args.old_font)
  File "C:\Users\nikolaus.waxweiler\AppData\Local\Python\Python36\site-packages\freetype\__init__.py", line 981, in __init__
    u_filename = c_char_p(_encode_filename(filename))
  File "C:\Users\nikolaus.waxweiler\AppData\Local\Python\Python36\site-packages\freetype\__init__.py", line 152, in _encode_filename
    encoded = filename.encode(sys.getfilesystemencoding())
AttributeError: 'WindowsPath' object has no attribute 'encode'
```

**Comment by rougier** [comment]
Thanks for the report. Do you have a fix?

**Comment by madig** [comment]
Not yet, currently busy with other things. On my todo list :)
